### ISSUE TITLE
PyTorch 1.0 compatibility

### ISSUE THREAD

**Issue by Avsecz** [kipoi/models#135]
After pytorch 1.0 has been released (yesterday), we got the following error https://circleci.com/gh/kipoi/models/569:

```: No module named 'torch.legacy'
Exception ignored in: <bound method tqdm.__del__ of 211MB [00:15, 15.5MB/s]>
Traceback (most recent call last):
  File "/opt/conda/envs/test-kipoi-DeepSEA__predict/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/opt/conda/envs/test-kipoi-DeepSEA__predict/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/opt/conda/envs/test-kipoi-DeepSEA__predict/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/opt/conda/envs/test-kipoi-DeepSEA__predict/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/opt/conda/envs/test-kipoi-DeepSEA__predict/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
ERROR [kipoi.cli.source_test] Model DeepSEA/predict failed: Command '['/opt/conda/envs/test-kipoi-DeepSEA__predict/bin/kipoi', 'test', '--batch_size', '4', '--source', 'kipoi', 'DeepSEA/predict']' returned non-zero exit status 1.
```

@krrome can you check why do we need `torch.legacy` and fix it?

**Comment by krrome** [comment]
fixed in https://github.com/kipoi/models/pull/136
