### ISSUE TITLE
FactorNet example file 404

### ISSUE THREAD

**Issue by krrome** [kipoi/models#137]
tests fail because `http://github.com/kipoi/models/blob/92b23ed62956d56eb457488b431fc27550ddbf32/FactorNet/template/dataloader_files/wgEncodeDukeMapabilityUniqueness35bp.chr22.bigWig?raw=true` is missing:

```
Downloading https://github.com/kipoi/models/blob/92b23ed62956d56eb457488b431fc27550ddbf32/FactorNet/template/dataloader_files/wgEncodeDukeMapabilityUniqueness35bp.chr22.bigWig?raw=true to /nfs/research1/stegle/users/rkreuzhu/.kipoi/models/FactorNet/CTCF/metaGENCODE_RNAseq_Unique35_DGF/downloaded/example_files/mappability_file
0.00B [00:00, ?B/s]Failed download. Trying https -> http instead. Downloading http://github.com/kipoi/models/blob/92b23ed62956d56eb457488b431fc27550ddbf32/FactorNet/template/dataloader_files/wgEncodeDukeMapabilityUniqueness35bp.chr22.bigWig?raw=true to /nfs/research1/stegle/users/rkreuzhu/.kipoi/models/FactorNet/CTCF/metaGENCODE_RNAseq_Unique35_DGF/downloaded/example_files/mappability_file
                   Traceback (most recent call last):
  File "/nfs/research1/stegle/users/rkreuzhu/conda-envs/kipoi-shared__envs__kipoi-py3-keras2/lib/python3.6/site-packages/kipoi/external/torchvision/dataset_utils.py", line 63, in download_url
    reporthook=gen_bar_updater(tqdm(unit='B', unit_scale=True))
  File "/nfs/research1/stegle/users/rkreuzhu/conda-envs/kipoi-shared__envs__kipoi-py3-keras2/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/nfs/research1/stegle/users/rkreuzhu/conda-envs/kipoi-shared__envs__kipoi-py3-keras2/lib/python3.6/urllib/request.py", line 223, in urlopen

...

  File "/nfs/research1/stegle/users/rkreuzhu/conda-envs/kipoi-shared__envs__kipoi-py3-keras2/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
@Avsecz can you move that file to S3?

**Comment by Avsecz** [comment]
I think i fix that one here 0b45364e534fe3e1e9f38626416187898d4330c4
