### ISSUE TITLE
DeepBind model doesn‘t exit

### ISSUE THREAD

**Issue by sunyolo** [kipoi/models#199]
Hello,
I'm quite new to kipoi, but I should praise your effort in advance for such great resource and concept.
I want to employ kipoi for further study about DeepBind.
However, when I run "kipoi ls" I get the following error:
`(pytorch36) C:\Users\suny\.kipoi\models>kipoi ls`
 `INFO [kipoi.sources] Update C:\Users\suny\.kipoi\models\
 Already up to date.`
`Traceback (most recent call last): 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
File "C:\Users\suny\Anaconda3\envs\pytorch36\Scripts\kipoi.exe\__main__.py", line 7, in <module> File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\__main__.py", line 105, in main command_fn(args.command, sys.argv[2:]) 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\cli\main.py", line 411, in cli_ls df = grp.list_models() 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 379, in list_models for model in self._list_components("model")]) 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 379, in <listcomp> for model in self._list_components("model")]) 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 429, in get_model_descr return self._get_component_descr(model, which="model") 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 754, in _get_component_descr return self.local_source._get_component_descr(component, which)
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 595, in _get_component_descr self.assert_is_component(component, which) 
File "c:\users\suny\anaconda3\envs\pytorch36\lib\site-packages\kipoi\sources.py", line 334, in assert_is_component raise 
ValueError("{} {} doesn't exist".format(which, component)) 
ValueError: model DeepBind\Arabidopsis_thaliana\RBP\D00283.001_RNAcompete_At_0284 doesn't exist`
Additionally, I have checked that there is indeed no model files of DeepBind on GitHub. So I was wondering if there are any other approaches to DeepBind models?
Thanks a million,
Sunyu

**Comment by krrome** [comment]
Hi Sunyu,
If you haven't added / changed anything in the "C:\Users\suny\.kipoi\models" folder could you try to just delete the "C:\Users\suny\.kipoi\" folder and uninstall + re-install kipoi? If that doesn't solve the problem please get back.

**Comment by suny1994** [comment]
Thank you. I've followed your suggestion but it didn't work. I think the key point is that, as we can see [https://github.com/kipoi/models/tree/master/DeepBind](url), there is indeed no model files of DeepBind on GitHub.  So,please, where can we get access to DeepBind models?

**Comment by krrome** [comment]
Regarding your question on DeepBind: The models are present on git and linked in the ".kipoi/models/DeepBind/models.tsv". This is a way to define Kipoi models differently - if you want to read up on how it works here is the explanation: http://kipoi.org/docs/contributing/06_dumping_models_programatically/

For some reason your kipoi version doesn't recognise this model definition correctly. I just tried again to reproduce the your error on an empty Ubuntu 18.04 using miniconda and python 3.6 (since I assume you are using 3.6 from your traceback), but for me everything worked. It is likely that the problem is related to executing on a Windows machine - Windows lacks many features in its file system / file management and we have had problems with Windows machines previously. I can't give you more details as I was not involved in programming that part of Kipoi. We can't develop for Windows as we simply don't have and Windows machines around. I am sorry that I couldn't help you more here, but I still hope that this was helpful.

Commands:
To setup miniconda and kipoi on Ubuntu 18.04 I did:
```
sudo apt-get update
sudo apt-get install build-essential --yes
# install miniconda
wget -O ~/miniconda.sh  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
# add to path
export PATH="/home/ubuntu/miniconda/bin:$PATH"
echo 'export PATH="/home/ubuntu/miniconda/bin:$PATH"' >> ~/.bashrc
# create new environment
conda create -n py36 python=3.6
source activate py36
pip install kipoi
kipoi ls
```
Please then continue following the getting started, e.g. create a model environment using `kipoi env create DeepBind` and then `source activate kipoi-DeepBind`, etc...
