### ISSUE TITLE
Framepool seems to miss required "biopython" package in environment.yml

### ISSUE THREAD

**Issue by Hoeze** [kipoi/models#211]
logs:
```
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 337, in __init__
    from Bio import bgzf
ModuleNotFoundError: No module named 'Bio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi/cli/main.py", line 265, in cli_predict
    for i, batch in enumerate(tqdm(it)):
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi_utils/external/torch/data.py", line 154, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoi_utils/external/torch/data.py", line 154, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "dataloader.py", line 112, in __getitem__
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoiseq/extractors/base.py", line 44, in __init__
    self.fasta = Fasta(self.fasta_file)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 999, in __init__
    build_index=build_index)
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/pyfaidx/__init__.py", line 344, in __init__
    "BioPython >= 1.73 must be installed to read block gzip files.")
ImportError: BioPython >= 1.73 must be installed to read block gzip files.
Exception ignored in: <bound method BaseExtractor.__del__ of <kipoiseq.extractors.base.FastaStringExtractor object at 0x7f2184168e10>>
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoiseq/extractors/base.py", line 18, in __del__
    return self.close()
  File "/opt/modules/i12g/anaconda/envs/kipoi-Framepool2/lib/python3.6/site-packages/kipoiseq/extractors/base.py", line 76, in close
    return self.fasta.close()
AttributeError: 'FastaStringExtractor' object has no attribute 'fasta'
```

**Comment by Karollus** [comment]
This issue is solved, no?

**Comment by Hoeze** [comment]
Yes, you're right
