### ISSUE TITLE
ValueError in Basenji model

### ISSUE THREAD

**Issue by visze** [kipoi/models#61]
Hi all. First thank you for developing kipoi! Great idea, practical and highly needed.

As a test I tried to use the Basenji model. After creating the environment I used the test comamnd which results in an tensorflow error. It seems that inputs are not define correctly:

```bash
(kipoi-Basenji)[user@secretServer]$ kipoi test Basenji --source=kipoi

INFO [kipoi.remote] Update /fast/users/schubacm_c/.kipoi/models/
Already up-to-date.
INFO [kipoi.remote] git-lfs pull -I Basenji/**
INFO [kipoi.remote] model Basenji loaded
INFO [kipoi.remote] git-lfs pull -I Basenji/./**
INFO [kipoi.remote] dataloader Basenji/. loaded
INFO [kipoi.data] successfully loaded the dataloader from /fast/users/schubacm_c/.kipoi/models/Basenji/dataloader.py::SeqDataset
/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO [kipoi.pipeline] dataloader.output_schema is compatible with model.schema
INFO [kipoi.pipeline] Initialized data generator. Running batches...
INFO [kipoi.pipeline] Returned data schema correct
Traceback (most recent call last):
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/cli/main.py", line 62, in cli_test
    mh.pipeline.predict_example(batch_size=args.batch_size)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/pipeline.py", line 82, in predict_example
    pred_list.append(self.model.predict_on_batch(batch['inputs']))
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/model.py", line 529, in predict_on_batch
    feed_dict=merge_dicts(feed_dict, self.const_feed_dict))
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 131072, 4) for Tensor 'inputs:0', which has shape '(2, 131072, 4)'
```

I guess that inputs are defined here https://github.com/kipoi/models/blob/ce94f6ccd62993e5ad09267baef63c7733bb78fa/Basenji/model.yaml#L45 and here https://github.com/kipoi/models/blob/ce94f6ccd62993e5ad09267baef63c7733bb78fa/Basenji/dataloader.yaml#L29

In the `dataload.py`you already wrote that Basenji strictly requires a batch size of 2. https://github.com/kipoi/models/blob/ce94f6ccd62993e5ad09267baef63c7733bb78fa/Basenji/dataloader.py#L51-L53 But this seems to be ignored in the command `kipoi test`

Cheers,
Max

**Comment by Avsecz** [comment]
Hi,

can you try:
```bash
kipoi test Basenji --source=kipoi --batch_size=2
```

I need to fix the snippet on the webpage and add `--batch_size=2`. I could only get Basenji to run with the batch_size of 2 (batch axis shape is hardcoded in the tf graph).

**Comment by Avsecz** [comment]
I'm thinking whether to build in more verbose error messages regarding the batch size restrictions or release this restriction from the tensorflow graph... I'll make an issue for releasing this restriction in Basenji

**Comment by Avsecz** [comment]
added an issue here https://github.com/kipoi/models/issues/62

**Comment by visze** [comment]
`--batch_size=2`: Perfect solution 😸 

But now I have different errors. When I first run it I get:

```
$ kipoi test Basenji --source=kipoi --batch_size=2
INFO [kipoi.remote] Update /fast/users/schubacm_c/.kipoi/models/
Already up-to-date.
INFO [kipoi.remote] git-lfs pull -I Basenji/**
INFO [kipoi.remote] model Basenji loaded
INFO [kipoi.remote] git-lfs pull -I Basenji/./**
INFO [kipoi.remote] dataloader Basenji/. loaded
INFO [kipoi.data] successfully loaded the dataloader from /fast/users/schubacm_c/.kipoi/models/Basenji/dataloader.py::SeqDataset
/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO [kipoi.pipeline] dataloader.output_schema is compatible with model.schema
INFO [kipoi.pipeline] Initialized data generator. Running batches...
INFO [kipoi.pipeline] Returned data schema correct
 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 3/5 [00:04<00:03,  1.58s/it]2018-03-16 11:21:32.183245: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at cwise_ops_common.cc:70 : Resource exhausted: OOM when allocating tensor with shape[2,131072,312] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

Traceback (most recent call last):
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2,131072,312] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[Node: cnn0/batch_normalization/moments/SquaredDifference = SquaredDifference[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](cnn0/conv1d/convolution/Squeeze, cnn0/batch_normalization/moments/mean)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/cli/main.py", line 62, in cli_test
    mh.pipeline.predict_example(batch_size=args.batch_size)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/pipeline.py", line 82, in predict_example
    pred_list.append(self.model.predict_on_batch(batch['inputs']))
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/model.py", line 529, in predict_on_batch
    feed_dict=merge_dicts(feed_dict, self.const_feed_dict))
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2,131072,312] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[Node: cnn0/batch_normalization/moments/SquaredDifference = SquaredDifference[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](cnn0/conv1d/convolution/Squeeze, cnn0/batch_normalization/moments/mean)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'cnn0/batch_normalization/moments/SquaredDifference', defined at:
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/cli/main.py", line 53, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/model.py", line 103, in get_model
    mod = AVAILABLE_MODELS[md.type](**md.args)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/kipoi/model.py", line 496, in __init__
    saver = tf.train.import_meta_graph(self.checkpoint_path + '.meta')
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1909, in import_meta_graph
    **kwargs)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 737, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2,131072,312] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[Node: cnn0/batch_normalization/moments/SquaredDifference = SquaredDifference[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](cnn0/conv1d/convolution/Squeeze, cnn0/batch_normalization/moments/mean)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

The second try is:

```
$ kipoi test Basenji --source=kipoi --batch_size=2
INFO [kipoi.remote] Update /fast/users/schubacm_c/.kipoi/models/
Already up-to-date.
INFO [kipoi.remote] git-lfs pull -I Basenji/**
INFO [kipoi.remote] model Basenji loaded
INFO [kipoi.remote] git-lfs pull -I Basenji/./**
INFO [kipoi.remote] dataloader Basenji/. loaded
INFO [kipoi.data] successfully loaded the dataloader from /fast/users/schubacm_c/.kipoi/models/Basenji/dataloader.py::SeqDataset
/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO [kipoi.pipeline] dataloader.output_schema is compatible with model.schema
INFO [kipoi.pipeline] Initialized data generator. Running batches...
INFO [kipoi.pipeline] Returned data schema correct
 60%|█████████████████████████████████████████▍                           | 3/5 [00:04<00:03,  1.64s/it]terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

and the third one goes through;

```
$ kipoi test Basenji --source=kipoi --batch_size=2
INFO [kipoi.remote] Update /fast/users/schubacm_c/.kipoi/models/
Already up-to-date.
INFO [kipoi.remote] git-lfs pull -I Basenji/**
INFO [kipoi.remote] model Basenji loaded
INFO [kipoi.remote] git-lfs pull -I Basenji/./**
INFO [kipoi.remote] dataloader Basenji/. loaded
INFO [kipoi.data] successfully loaded the dataloader from /fast/users/schubacm_c/.kipoi/models/Basenji/dataloader.py::SeqDataset
/fast/users/schubacm_c/miniconda3/envs/kipoi-Basenji/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO [kipoi.pipeline] dataloader.output_schema is compatible with model.schema
INFO [kipoi.pipeline] Initialized data generator. Running batches...
INFO [kipoi.pipeline] Returned data schema correct
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:08<00:00,  1.68s/it]
INFO [kipoi.pipeline] predict_example done!
INFO [kipoi.cli.main] Successfully ran test_predict
```

If I repeat it it returns one of the previous errors... Well it can be something really machine specific (GPU, CUDA and tensorflow hiccups or just memory issues). So I tried a different one (pure CPU). Here it works perfect. 

One thing I noticed that causes maybe problems is the installed tensorflow version. You are using pip and install the newest version (v1.6). But tensorflow requires cuda 9.0 and cuDNN7.0. (the latter was not available on the GPU). Normally I am running tensorflow v1.4.1 installed by conda (`tensorflow-gpu`) which avoids the cuda/cuDNN incompatibilities. But a newer version is not available yet.

By uninstalling tensorflow and tensorboard (``pip uninstall tensorboard tensorflow) and installing tensorboard from conda (`conda install tensorboard-gpu`) I was able to run the Basenji model on the GPU and also using the GPUs. 

Also not every created model will work with any tensorflow version. I would suggest to fix the version in the conda environment to the one that were used to build the model. 


You can close this issue. I think it is resolved. Just the my other lines as some comments (maybe helpful or maybe not).

**Comment by Avsecz** [comment]
glad the `batch_size` worked for you. 

Running tensorflow can sometimes (still) be tricky (especially with GPU's) although it has improved a lot. If you are installing it on a gpu capable maching use the `--gpu` flag with `kipoi env create` .i.e.:

```bash
kipoi env create Basenji --gpu
```
This will install `tensorflow-gpu` instead of `tensorflow`.

Regarding fixing version. I don't want to strictly freeze the versions too much as it prevents people from using multiple models simultaneously in the same environment. I think setting `>=,<=` restrictions rather than `==` for package dependencies is better (as python packages do in `setup.py`). We are testing all the tests every night to make sure all the current dependencies from pypi/conda still work for all the models. 

### Using a custom version of a package for a model

If you find you have a special setting on your server and would like to use a particular tensorflow version, I suggest doing the following steps:

```bash
# export the conda environment file for a model
kipoi env export Basnji --gpu -o Basenji-env.yml
```

then edit the `Basenji-env.yml` file containing the dependencies (specify the tensorflow version that works for your particular CUDA/cuDNN setup) and create the environment:

```bash
conda env create --file Basenji-env.yml
```

**Comment by Avsecz** [comment]
I'm thinking whether one could override some of the packages already at the `env create` command:

```bash
kipoi env create Basenji --gpu --override_pip='tensorflow-gpu==1.4'
```

However, this might become complicated quite quickly

**Comment by Avsecz** [comment]
I'll close the issue
