### ISSUE TITLE
DeepBind not functional

### ISSUE THREAD

**Issue by krrome** [kipoi/models#65]
As in title, perhaps there is something wrong with the weights file? Any idea?
```
kipoi test -i DeepBind/D00001.001 --source kipoi
...
INFO [kipoi.remote] git-lfs pull -I DeepBind/D00001.001/**
INFO [kipoi.remote] git-lfs pull -I DeepBind/template/**
INFO [kipoi.remote] model DeepBind/D00001.001 loaded
INFO [kipoi.remote] git-lfs pull -I DeepBind/D00001.001/./**
INFO [kipoi.remote] git-lfs pull -I DeepBind/template/**
INFO [kipoi.remote] dataloader DeepBind/D00001.001/. loaded
INFO [kipoi.data] successfully loaded the dataloader from .../.kipoi/models/DeepBind/D00001.001/dataloader.py::SeqDataset
.../conda-envs/kipoi/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 230, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../conda-envs/kipoi/bin/kipoi", line 11, in <module>
    load_entry_point('kipoi', 'console_scripts', 'kipoi')()
  File "...kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "...kipoi/cli/main.py", line 53, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "...kipoi/model.py", line 103, in get_model
    mod = AVAILABLE_MODELS[md.type](**md.args)
  File "...kipoi/model.py", line 223, in __init__
    self.model = load_model(weights, custom_objects=self.custom_objects)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/engine/topology.py", line 2510, in from_config
    process_layer(layer_data)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/engine/topology.py", line 2496, in process_layer
    custom_objects=custom_objects)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/layers/core.py", line 711, in from_config
    function = func_load(config['function'], globs=globs)
  File ".../conda-envs/kipoi/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 234, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

**Comment by Avsecz** [comment]
which keras version are you using?

**Comment by Avsecz** [comment]
can you install a fresh conda environment and run the same thing? It should work there

**Comment by krrome** [comment]
I installed 2 new environments py3.5 and py3.6 and both times it's the same things. there seems to be a problem when storing weights and architecture in one hdf5 file and if the python, keras, tensorflow etc. versions don't match up exactly if I understand (https://github.com/keras-team/keras/issues/7440) correctly..

**Comment by Avsecz** [comment]
just to be sure: did you install new environments via kipoi? DeepBind works perfectly fine for me

**Comment by krrome** [comment]
yep they were only fresh requirements. must be the python 2.7 requirement then - should we/I port it to a python 3 compatible version? I think it's not ideal to be restricted to python 2.7 and since it's a Keras model there should be no need for that unless its a dataloader issue... but the problem I get is from Keras and might be related to the version of Keras used in DeepBind -> see link to keras team issue before

**Comment by Avsecz** [comment]
agree. Let's port it to python 3 then. I'll make a new issue and close this one
