### ISSUE TITLE
Getting output to standard out (instead of saving to a VCF)

### ISSUE THREAD

**Issue by pjshort** [kipoi/models#95]
I am trying to annotate a VCF file with deepSEA results and would like to have the output VCF go to standard out, so I can pipe straight to another script.

I tried the following:

```kipoi postproc score_variants DeepSEA/variantEffects --dataloader_args '{"fasta_file": "Homo_sapiens.GRCh37.74.dna.chr.fasta"}' -i min.vcf ```

using the following simple vcf:

##fileformat=VCFv4.1
##contig=<ID=1,length=249250621,assembly=b37>
##reference=file:Homo_sapiens_assembly19.fasta
#CHROM  POS ID  REF ALT
1       10002   -       T       A
1       10002   -       T       C
1       10002   -       T       G

This results in the following error:

Traceback (most recent call last):
  File "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/lib/python3.5/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/lib/python3.5/site-packages/kipoi/cli/postproc.py", line 658, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/lib/python3.5/site-packages/kipoi/cli/postproc.py", line 118, in cli_score_variants
    dir_exists(os.path.dirname(args.output_vcf), logger)
  File "/Users/ps14/anaconda3/envs/kipoi-DeepSEA__variantEffects/lib/python3.5/posixpath.py", line 148, in dirname
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

If you could help me figure out how to print to standard out I would really appreciate it! Thank you!

**Comment by Avsecz** [comment]
Good idea. We'd have to add this functionality.

**Comment by pjshort** [comment]
Thank you, @Avsecz!
